spring:
  datasource:
    url: "jdbc:mysql://gz-cdb-eg2qxhpr.sql.tencentcdb.com:59979/knowledge?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&useSSL=false&connectTimeout=10000&autoReconnect=true&tcpRcvBuf=1024000&allowMultiQueries=true"
    username: "root"
    password: "*FengPoLang"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

mybatis-plus:
  global-config:
    db-config:
      id-type: auto